spring:
  application:
    name: OpenGroup
  profiles:
    active: test
  thymeleaf:
    check-template-location: false

server:
  port: 8085

azure:
  storage:
    account-name: "cidastore"
    account-key: "OofPa4ovwX8556wyVanY8OPUP5pnxAHLCdYTPoujBqhpU/2Aty6uQfbnoaTA0Rcgb1cRVsq/oPwQ+AStTpvISg=="
    container-name: "teste-container"
    connection-string: "DefaultEndpointsProtocol=https;AccountName=cidastore;AccountKey=OofPa4ovwX8556wyVanY8OPUP5pnxAHLCdYTPoujBqhpU/2Aty6uQfbnoaTA0Rcgb1cRVsq/oPwQ+AStTpvISg==;EndpointSuffix=core.windows.net"

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
#    supported-submit-methods: { "get", "put", "post", "delete", "options", "head", "patch", "trace"}
#
#  api-docs:
#    enabled: true