spring:
  application:
    name: OpenGroup
  profiles:
    active: dev
  thymeleaf:
    check-template-location: false

server:
  port: 8085

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
#    supported-submit-methods: { "get", "put", "post", "delete", "options", "head", "patch", "trace"}
#
#  api-docs:
#    enabled: true